### ISSUE TITLE
Revert back to default pref

### ISSUE THREAD

**Issue by BAT-FA** [yannbertrand/mac-setup#7]
Is there a way to revert all changes back to normal/default that was done after running (mac-setup)?

**Comment by yannbertrand** [comment]
There is not.

You should be able to reset `defaults` command using the `defaults delete` command. Example: https://macos-defaults.com/dock/tilesize.html#reset-to-default-value

[Oh My Zsh uninstall procedure is documented on their GitHub](https://github.com/ohmyzsh/ohmyzsh#uninstalling-oh-my-zsh).

[Homebrew uninstall script is available from their website](https://docs.brew.sh/FAQ#how-do-i-uninstall-homebrew).

Other than that there is a few created folders and config files that you should clean or delete.
